version: '3'

networks:
  workshop:
    driver: bridge

services:
  php:
    container_name: workshop_php
    build: ./docker/php
    volumes:
    - .:/var/www/html
    working_dir: /var/www/html
    networks:
    - workshop

  nginx:
    container_name: workshop_nginx
    image: nginx:stable
    ports:
    - 80:80
    volumes:
    - .:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
    - workshop

  mongodb:
    container_name: workshop_db
    image: bitnami/mongodb:latest
    networks:
    - workshop